### ISSUE TITLE
Sign-up Section

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#10]
**User Story:**
- As MariaVetClinicWorker I would like the site to have a clear sign-up section so that I know what information is needed to create an account for CASI.

**Specifics:**
- Create a sign-up page allowing the user to sign up with their email, create a password for the app, and specify their vet clinic.
- This page will also include an ethics page that the user will have to accept prior to creating their CASI Survey account. 
- **Estimated time of completion: 3hr**

**TODO:**
* Before development:
  - [x] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [x] Write up the interface document for this feature
  - [x] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [x] Create text fields for the email, password, and vet clinic name
      - Enforce that the password has to be at least a length of 8 characters 
      - For added security, the password must contain at least 1 uppercase and 1 special character
      - The password should also contain a numerical value. 
  - [x] Create a pop up link for the ethics section
  - [x] Have a check box for the ethics section, that will be required to be checked before continuing
  - [x] Make the email, password, vet clinic name, and ethics check box be a required field
  - [ ] Write a document that explains the logic behind your code and any relevant information

**Comment by kurtp21** [comment]
This has been completed
