### ISSUE TITLE
Design and Finalize Database Schema

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#122]
**TODO:**
- [x] Design the database tables that will be used to store the data related to the project 
- [x] Document the schema once completed 
- [x] Conduct a code inspection on the final design

**Comment by kurtp21** [comment]
This has been completed
