### ISSUE TITLE
SQL Queries

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#131]
**Specifics:**
- Look over the updated database schema and design + create the SQL queries that will be used for storing/getting data from our database
- Make sure that the queries that you create cover all the use cases that are necessary for the CASI app.
- As a reference, look at back-end/src/app/adapter/SQLRepositories/User/UserSQLRepository.ts
    - There are already queries created in this file, but now that the schema is updated make sure these queries are updated to match the new schema.

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Update the old queries that were made for the old DB schema to match with the new DB schema.
  - [ ] Create a query for signup requests (this will be an insert into the request table)
  - [ ] Create a query for password reset requests (this will be an insert into the request table)
  - [ ] Create a query for creating a survey
  - [ ] Create a query for creating a question (includes: standard questions [un-nested/nested], multiple choice options, and dropdown options
  - [ ] Create a query for getting all questions required for a survey (the answerQuestionMap and surveyQuestionMap will be needed)
  - [ ] Create a query for getting all of the individual user responses to a survey
  - [ ] Create other potential useful queries that we might need (The ones mentioned above are the ones the dev lead can think of)
  - [ ] Write a document that explains the logic behind your code and any relevant information
