### ISSUE TITLE
Admin Approval of SIgn-up Requests

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#132]
**Specifics:**
- Implement the logic for accepting the user signup requests on the admin side for the CASI app.
- Remember that the user will be signing up with an email, password, and clinic name, along with agreeing to ethics.
- When the admin approves a request, automatically generate a user ID for the user, that will be sent to the [ userID Requests Status page] (this will be a separate issue that will be worked on) upon approval of the user's sign-up request 

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Create a separate page on the admin dashboard that will show all the signup requests (Call it signup requests)
  - [ ] For each user in that request table, create a request box for them that will be shown on the signup requests page 
      - Make this box have an approve and reject box, that will handle the status of the user's request
  - [ ] When the admin approves of the signup request, automatically generate a userID for that user
      - When the admin clicks on the approve button, this action will trigger the ID generator and create a randomized ID for that user
  - [ ] When the user ID has been generated, insert the user's data along with their randomized userID into the User table in our database and change their request status to approved in the Request table 
  - [ ] When the admin rejects the user's signup request, change the user's signup request status to rejected in the Request table.
  - [ ] Write a document that explains the logic behind your code and any relevant information
