### ISSUE TITLE
POST /api/survey

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#168]
**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Write unit tests before implementing code 
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Implement the Survey Interface file
  - [ ] Implement the Survey Repository file 
  - [ ] implement the survey service file
  - [ ] Add the route into the SurveyController.ts
  - [ ] Implement the survey handler file for [ POST /api/survey ]
