### ISSUE TITLE
GET /api/survey/:surveyId/response

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#170]
**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests before implementing code 
  - [ ] Create a logging document
  - [ ] Write unit tests before implementing code 
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Implement the Survey Response Interface file
  - [ ] Implement the Survey Response Repository file 
  - [ ] implement the survey Response service file
  - [ ] Add the route into the SurveyController.ts
  - [ ] Implement the survey handler file for [ GET /api/survey/:surveyId/response ]
