### ISSUE TITLE
POST /api/survey/:surveyId

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#174]
**TODO:**
* Before development:
  - [ ] Review the API document for the specifics of the API ([API-Design.pdf](https://drive.google.com/file/d/1XrQd4P7BgarYz7ITMr3i1H0MAr-K5AGr/view?usp=drive_link), pg: 6)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests before implementing code 
  - [ ] Create a logging document
  - [ ] Write unit tests before implementing code 
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Implement the User Submit Question Answer Interface file
  - [ ] Implement the User Submit Question Answer Repository file 
  - [ ] implement the User Submit Question Answer service file
  - [ ] Add the route into the SurveyController.ts
  - [ ] Implement the user submit survey answer handler file for [ POST /api/survey/:surveyId/answer ]
