### ISSUE TITLE
GET /api/survey

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#176]
**TODO:**
* Before development:
  - [x] Review the API document for the specifics of the API ([API-Design.pdf](https://drive.google.com/file/d/1XrQd4P7BgarYz7ITMr3i1H0MAr-K5AGr/view?usp=drive_link), pg: 8)
  - [x] Write up the interface document for this feature
  - [x] Write unit tests before implementing code 
  - [x] Create a logging document
  - [x] Write unit tests before implementing code 
  - [x] Peer review with your tester pair before development
* After documents are completed:
  - [x] Implement the User Get Survey Object List Interface file
  - [x] Implement the User Get Survey Object List Repository file 
  - [x] Implement the User Get Survey Object List service file
  - [x] Add the route into the UserController.ts
  - [x] Implement the user get survey object list handler file for [ GET /api/survey ]
