### ISSUE TITLE
User ID Generation

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#18]
**User Story:**
- As Tasha Epp I would like to generate the user ID myself so that I have control over who will be able to participate in the surveys.

**Specifics:**
- Create an option for the admin to randomly generate an ID for the user who signed up for the CASI app. This should be on the admin dashboard side. 
- **Estimated time of completion: 1hr**

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Design an algorithm that will create a randomized user ID for the users
      - This should contain the following characters: A-Z, a-z, 0-9
      - Prefered a length of 6 characters, max of 8 characters 
  - [ ] Create a button called "Generate ID" which will generate the ID with the algorithm created
  - [ ] Make it so that the admin has to confirm the ID before assigning it to the user
      - Ex: "Do you want ID "xLss54Ol1" to be assigned to the user ??" --> Confirm
  - [ ] When the admin confirms the generated ID for the user, notify the user of their newly generated ID assigned to them
  - [ ] Follow the UI design for the style of this section
  - [ ] Write a document that explains the logic behind your code and any relevant information
