### ISSUE TITLE
Deletion Of Users

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#19]
**User Story:**
- As Tasha Epp I would like to have the option to remove users from the app so that if necessary which might not happen, I can delete them with ease.

**Specifics:**
- Create a section on the admin dashboard, that will allow the Admin to delete any users that they want. When the user is deleted, make sure their data is soft deleted from the database and that the user will not get a notification.
- **Estimated time of completion: 1.5hr**

**TODO:**
* Before development:
  - [x] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Create a section on the admin dashboard that will allow the admin a list of all users of the CASI app.
  - [ ] Add a remove button beside each of the users in that list, so the admin can remove the user if they so wish it.
  - [ ] When the user is removed by the admin, soft delete their data from the database:
      - Soft delete means that there is an extra column in the user databases that says deleted
      - It is a boolean column that specifies if the user's data has been deleted or not
      - I user's data will just be marked as deleted, compared to being actually deleted
      - This way we can still recover that user if the Admin chooses to do so.
  - [ ] Follow the UI mockups for the design of this page
  - [ ] Write a document that explains the logic behind your code and any relevant information
