### ISSUE TITLE
Accepting Password Reset Requests

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#20]
**User Story:**
- As Tasha Epp I would like to manually accept the user's password reset requests and notify the user automatically that I have approved their request so that I can handle the resets properly and securely myself.

**Specifics:**
- Create a page in the admin dashboard that will allow the admin to see all password requests sent and allow the admin to either accept or reject those requests. 
- **Estimated time of completion: 1hr**

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Create a page that will show all the password reset requests
  - [ ] Create an accept and reject button for each 
  - [ ] When the user's request has been rejected, send them a notification that their request has been denied. 
  - [ ] When the user's request has been accepted, send them an invite link notification to set a new password. 
  - [ ] Follow the UI mockups for the styling of this section.
  - [ ] Write a document that explains the logic behind your code and any relevant information

**Comment by kurtp21** [comment]
This will be scratched.
