### ISSUE TITLE
Database Migration

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#36]
Find a solution for the database migration for our database, so that we can just run a command that will pull recent changes made to the database.

**TODO**
- [x] Find a viable and compatible package that will allow database migration for our app.
- [x] Get the package to work with our project
- [x] Make sure you run the commands needed and that they work before pushing
- [ ] Write a document that explains the database migration and the set of commands that the developer needs to know about
