### ISSUE TITLE
Login Section

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#38]
**User Story:**
- As MariaVetClinicWorker I would like the site to have a clear login section so that I know where to input my generated ID, and password, and where to click when I need to reset my password.

**Specifics**
- Create a login section for the CASI app, that will allow users who have an account for the CASI survey to login to access the surveys
- **Estimated time of completion: 3hrs**

**TODO:**
* Before development:
  - [x] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [x] Write up the interface document for this feature
  - [x] Write unit tests for this feature
  - [x] Create a logging document
  - [x] Peer review with your tester pair before development
* After documents are completed:
  - [x] Have a text box for the clinic ID and password
  - [x] Have a "Login" button that will log the user into the CASI app
  - [x] Create a separate user ID and password for the admin
      - Keep track of the ID and password you used for the admin, we will give this to our admin later on
      - When the admin logs in with these credentials, it should take them into the admin dashboard of the CASI app.
  - [x] Add a sign-up link under the text boxes, with text that tells the user to sign up if they haven't done so
  - [x] Have a smooth transition into the home page of the CASI app for the user or the CASI admin dashboard for the admin
  - [x] Follow the design mockups for the login page
  - [x] Write a document that explains the logic behind your code and any relevant information
