### ISSUE TITLE
Survey Creation/Edditing for the Admin

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#39]
**User Story:**
- As Tasha Epp I would like a Survey Monkey type of survey creation so that when I need to add a new survey question, I can do so easily.

**Specifics:**
- Create a section for the admin dashboard that will allow the admin to create and edit surveys. 
- **Estimated time of completion: 2hr**

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Have a button that will allow Dr. Epp to create a survey
  - [ ] Have a button that will allow Dr. Epp to edit a created survey
  - [ ] Give it a set format
      - Use the SurveyMonkey template that  Dr. Epp gave us as a guide
      - Use the mockups that Evander created
  - [ ] Make the survey creation/editing user-friendly and easy to use
  - [ ] Allow the creation of nested questions.
  - [ ] Write a document that explains the logic behind your code and any relevant information

**Helpful Resources**
- [Figma UI Mockups](https://www.figma.com/file/JKxRRE9YYOCVaJPBPR3T3E/Casi-mockup?type=design&node-id=5%3A413&mode=design&t=al2zGU24uQHDMtPy-1)
