### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#53]
Finalize and document our CI/CD pipeline structure. 

**TODO** 
- [ ] Create the file that will run the CI/CD pipeline automatically
- [ ] The stages it should have, but not limited to is:
    1.  Source
    2. Build
    3. Test
    4. Deployment
- [ ] Write documentation of how the CI/CD pipeline works and what it would do.

**Useful resource** 
- [CI/CD Pipeline](https://semaphoreci.com/blog/cicd-pipeline#:~:text=A%20CI%2FCD%20pipeline%20automates,and%20enable%20fast%20product%20iterations.)
