### ISSUE TITLE
Server Configurations

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#54]
Configure the .env files in our server, for the connection of our database to the server.

**TODO**
- [ ] Needs to be configured for both development and production 
- [x] Specify the:
    1. IP Address
    2. Port
    3. Database password & name
- [ ] Write a document that explains the configurations that were made on the .env files and other relevant files     
- [ ] Make sure it is tested and works properly without any errors.
