### ISSUE TITLE
Input Sanitization and Validation

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#55]
Design and create the sanitization and validation for the inputs passed through by the user. This will make sure our application will be secure and safe. This also includes _"Prepared Statements"_ for the database

**TODO**
- [ ] Design the methods for the input sanitization and validation
- [ ] Create those methods so they can be used
- [ ] Do the same thing for the prepared statements for our database
    - If you find a package that will do this for us, that'd be great. To take some load off of your chest
- [ ] Create a document for the designs and methods you have created, to understand how they work and how they should be used

**Helpful Resources**
- [Securing User Inputs](https://medium.com/@gwenilorac/html-injection-2d0d5b618898#:~:text=Another%20major%20aspect%20of%20front,entirely%20on%20the%20front%20end.)
- [How to use Sanitization and Validation](https://www.esecurityplanet.com/endpoint/prevent-web-attacks-using-input-sanitization/)
- [Securing Your App](https://www.tiny.cloud/blog/input-sanitization/)
