### ISSUE TITLE
JWT Security

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#57]
Look into JWT for the security of our app. Check if it would work for our product and if it does, design and create what is needed for it to work.

**Todo**
- [ ] Understand how it is secure and how it would work for our app.
- [ ] If JWT works for our app:
    - Make simple JWT's and test them to make sure it is compatible 
    - Design and implement the JWT after testing is done
- [ ]  Write a documentation explaining how JWT works and how it is used in our app. 

**Helpful Resources**
- [JASON Web Tokens](https://jwt.io/)
- [JWT in TypeScript with Express](https://dev.to/juliecherner/authentication-with-jwt-tokens-in-typescript-with-express-3gb1)
- [JWT Authentication with Typescript and Express](https://dev.to/cristain/how-to-implement-jwt-authentication-using-node-express-typescript-app-2023-2c5o)
