### ISSUE TITLE
Update UI Desgin

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#58]
Specifically the admin side of the UI design. Update the current admin UI because it is for desktop, change it to mobile. Make the Figma design responsive.

**TODO**
- [ ] Review the current UI mockups.
- [ ] Re-design the admin UI for the app to make it compatible with mobile devices instead of desktops.
- [ ] Make the design responsive.
    - Figma has this option
    - In Figma, you can make the design mimic how it will flow when the user is using the app.
- [ ] Write a document that explains the changes made to the UI designs.
- [ ] After completion, conduct an inspection with at least 3 other individuals.
    - Recommended: have the past design leads and dev lead be part of the inspection.

**Helpful Resources**
- [Responsive Figma](https://designcode.io/figma-handbook-responsive-design)
- [Figma Responsive Tutorial](https://www.youtube.com/watch?v=gwiX0oASlEw&ab_channel=DesignWithArash)

**Comment by kurtp21** [comment]
Completed the inspection of the UI mockup. Which was shown to our stakeholder, where she provided some feedback back on the style and flow of the UI for the CASI app.
