### ISSUE TITLE
Database Connection Pooling

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#59]
Configure the backend code to make it connect to the database through pooled connections.

**TODO**
- [x] Use pooled configurations to make the backend code communicate to the database
- [x] Before submitting a merge request, make sure it is tested and works without crashing or creating an error.
- [x] Write a document that explains how the pooled connection works with our backend and database
    - Along with any required commands or required changes that the developer needs to make themselves.
