### ISSUE TITLE
Survey Notification

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#7]
**User Story**
- As MariaVetClinicWorker I would like to receive notifications so that I can always know what is going on regarding the survey releases, not done surveys, password request approval, etc.

**Specifics:**
- Develop the notifications of the CASI App, this involves the notifications that the user will see when the admin (Dr. Epp) publishes a new quarterly survey. 
- The notification should show how many days they have left to complete the survey, how many days until the next survey release after completing the current survey. 

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Follow the UI designs for the style of the notification that will be shown to the user 
  - [ ] Create a countdown timer notification that will show the remaining days, hours, and minutes of when the next quarterly survey will be published
      - Make sure that this notification will only be shown when the user has completed the current quarterly survey
  - [ ] Create a reminder notification that will remind the user to do the quarterly survey
      - It is up to you how often this reminder will be shown to the user
      - Dr. Epp said that we should allow the user to have roughly around a week or two of a timeframe for them to complete the survey
  - [ ] Write a document that explains the logic behind your code and any relevant information
