### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#8]
**User Story:**
- As MariaVetClinicWorker I would like to have an option to reset my password so that in case I forget my password, I will be able to reset it.

**Specifics:**
- Create a section for the user that allows them to reset their password if they ever forget it. When they reset their password and click on the reset link, it should send them to a different section and ask them to input their user ID and vet clinic name. Then they would need to click a button that says "Send Reset Request", which will send a request to the admin for a password rest. Their request will need to be accepted by the admin before the user is allowed to input a new password for their account. 

**TODO:**
* Before development:
  - [ ] Create a diagram (activity, use-case, or any type of diagram best suited for this feature)
  - [ ] Write up the interface document for this feature
  - [ ] Write unit tests for this feature
  - [ ] Create a logging document
  - [ ] Peer review with your tester pair before development
* After documents are completed:
  - [ ] Create a separate page for redirecting the user to fill out their password reset request form
      - This will include an email and user ID textbox
  - [ ] Have a button that says, "Send Request"
  - [ ] At the top of the page, have a small info text that informs the user about what the page is
  - [ ] When the user sends the request, make sure a notification is sent to the admin dashboard that will notify the admin about the password reset request that was just sent
  - [ ] Create a page on the admin dashboard that is dedicated to viewing and accepting/denying user password reset requests
  - [ ] When the admin accepts/denies the password reset request, notify the user about the status of their request
      - If the request is accepted, allow the user to reset their password with a new one, and redirect them to a reset password page. In this page the user will be required to input their email and user ID along with the new password they chose and a confirmation of that password.
      - If the request is denied, send the user a notification that their request has been denied. 
  - [ ] Follow the CASI UI designs to have a nice flow with styling for the app and this password reset page style
  - [ ] Write a document that explains the logic behind your code and any relevant information

**Comment by kurtp21** [comment]
This will be scratched.
