### ISSUE TITLE
Logging Framework

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#85]
Implement the logging framework and its classes that will be used to test the code that the developers implemented. 

**TODO:**
  - [ ] Peer review with your tester pair before development
  - [ ] Write a document that explains the logic behind your code and any relevant information
  - [ ] Test the logging classes to make sure they work and detect errors
  - [ ] Make the logger log to the terminal and also to a separate logDoc.txt file
      - The file can be any name, just make sure you specify it in the documents. 
  - [ ] Create a document that explains the logging framework you implemented, along with any necessary information.
  - [ ] Conduct a peer review with your pair, making sure that the meeting is documented.
