### ISSUE TITLE
Dependency Injection Files

### ISSUE THREAD

**Issue by kurtp21** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-1#88]
**Specifics:**
- Set up the dependency injection files that are needed for our repo
- **Estimated time of completion: 1hr**

**TODO:**
- [x] Complete the dependency injection files 
- [ ] Conduct a peer review after completion of the issue and document the meeting
- [ ] Create a document that explains the use of the files and how they work with our repo, and any other relevant information
